-- MySQL Script generated by MySQL Workbench
-- 05/08/16 14:11:46
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema etp
-- -----------------------------------------------------
-- 企业库

-- -----------------------------------------------------
-- Schema etp
--
-- 企业库
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `etp` DEFAULT CHARACTER SET utf8 ;
USE `etp` ;

-- -----------------------------------------------------
-- Table `etp`.`etp_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `etp`.`etp_user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `account` VARCHAR(20) NOT NULL DEFAULT '' COMMENT '用户账号',
  `password` VARCHAR(32) NOT NULL DEFAULT '' COMMENT '用户账号密码',
  `email` VARCHAR(100) NOT NULL DEFAULT '' COMMENT '邮箱地址',
  `registertime` INT(10) NOT NULL DEFAULT 0 COMMENT '注册时间',
  `logintime` INT(10) NOT NULL DEFAULT 0 COMMENT '上次登录时间',
  `loginip` INT(10) NOT NULL DEFAULT 0 COMMENT '上次登录Ip',
  `locks` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否被锁定(0未 1锁定)',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `account` (`account` ASC))
ENGINE = MyISAM
COMMENT = '用户表';


-- -----------------------------------------------------
-- Table `etp`.`etp_userinfo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `etp`.`etp_userinfo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(20) NOT NULL DEFAULT '' COMMENT '用户昵称',
  `userpic` VARCHAR(100) NOT NULL DEFAULT '' COMMENT '用户头像',
  `truename` VARCHAR(20) NOT NULL DEFAULT '' COMMENT '真实名称',
  `location` VARCHAR(20) NOT NULL DEFAULT '' COMMENT '所在地',
  `sex` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '性别(0:男 1:女)',
  `day` VARCHAR(15) NOT NULL DEFAULT '' COMMENT '用户生日',
  `intro` VARCHAR(100) NOT NULL DEFAULT '' COMMENT '一句话介绍自己',
  `blog` VARCHAR(100) NOT NULL DEFAULT '' COMMENT '用户博客地址',
  `msn` VARCHAR(100) NOT NULL DEFAULT '' COMMENT '用户msn地址',
  `qq` INT(11) UNSIGNED NOT NULL DEFAULT 0 COMMENT 'QQ号码',
  `uid` INT NOT NULL COMMENT '所属用户id',
  PRIMARY KEY (`id`),
  INDEX `uid` (`uid` ASC))
ENGINE = MyISAM
COMMENT = '用户个人信息表';


-- -----------------------------------------------------
-- Table `etp`.`etp_videoclassify`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `etp`.`etp_videoclassify` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(20) NOT NULL DEFAULT '' COMMENT '类别名称',
  `faceurl` VARCHAR(100) NOT NULL DEFAULT '' COMMENT '类别封面图',
  `fid` INT NOT NULL DEFAULT 0 COMMENT '分类父级ID(0为最高级别)',
  PRIMARY KEY (`id`))
ENGINE = MyISAM
COMMENT = '视频分类(无限极)';


-- -----------------------------------------------------
-- Table `etp`.`etp_manages`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `etp`.`etp_manages` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `account` VARCHAR(20) NOT NULL DEFAULT '' COMMENT '管理员账号',
  `password` VARCHAR(32) NOT NULL DEFAULT '' COMMENT '管理员密码',
  `logintime` INT(10) NOT NULL DEFAULT 0 COMMENT '上次登录时间',
  `loginip` VARCHAR(50) NOT NULL DEFAULT '' COMMENT '上次登录IP',
  `locks` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '管理员是否被锁定(0未锁定,1锁定)',
  `level` VARCHAR(100) NOT NULL DEFAULT '' COMMENT '管理员权限表',
  `logins` INT NOT NULL DEFAULT 1 COMMENT '管理员登录次数',
  PRIMARY KEY (`id`))
ENGINE = MyISAM
COMMENT = '管理员表';


-- -----------------------------------------------------
-- Table `etp`.`etp_video`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `etp`.`etp_video` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `videoname` VARCHAR(20) NOT NULL DEFAULT '' COMMENT '视频名称',
  `playcount` INT NOT NULL DEFAULT 0 COMMENT '播放次数',
  `comment` INT NOT NULL DEFAULT 0 COMMENT '评论次数',
  `videourl` VARCHAR(100) NOT NULL DEFAULT '' COMMENT '视频地址',
  `videopicurl` VARCHAR(100) NOT NULL DEFAULT '' COMMENT '视频封面图',
  `topcount` INT NOT NULL DEFAULT 0 COMMENT '点赞人数',
  `fid` TINYINT(20) NOT NULL DEFAULT 0 COMMENT '父级ID(用于分类 默认0为最高级)',
  `uploadtime` INT(10) NOT NULL DEFAULT 0 COMMENT '上传时间',
  `keepcount` INT NOT NULL DEFAULT 0 COMMENT '收藏次数',
  `cid` INT UNSIGNED NOT NULL COMMENT '所属视频分类ID',
  `mid` INT UNSIGNED NOT NULL COMMENT '所属管理员id',
  PRIMARY KEY (`id`),
  INDEX `cid` (`cid` ASC),
  INDEX `mid` (`mid` ASC))
ENGINE = MyISAM
COMMENT = '视频表';


-- -----------------------------------------------------
-- Table `etp`.`etp_musicclassify`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `etp`.`etp_musicclassify` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(20) NOT NULL DEFAULT '' COMMENT '分类名称',
  `fid` INT NOT NULL DEFAULT 0 COMMENT '父级别ID(0代表最高级别)',
  `faceurl` VARCHAR(100) NOT NULL DEFAULT '' COMMENT '分类图片地址',
  PRIMARY KEY (`id`))
ENGINE = MyISAM
COMMENT = '音乐分类(这里只做2级)表';


-- -----------------------------------------------------
-- Table `etp`.`etp_music`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `etp`.`etp_music` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `musicname` VARCHAR(20) NOT NULL DEFAULT '' COMMENT '歌曲名',
  `playcount` INT NOT NULL DEFAULT 0 COMMENT '音乐播放次数',
  `musicurl` VARCHAR(100) NOT NULL DEFAULT '' COMMENT '音乐地址',
  `keepcount` INT NOT NULL DEFAULT 0 COMMENT '收藏次数',
  `uploadtime` INT(10) NOT NULL DEFAULT 0 COMMENT '上传时间',
  `cid` INT UNSIGNED NOT NULL COMMENT '所属音乐类别ID',
  `mid` INT UNSIGNED NOT NULL COMMENT '所属管理员ID',
  PRIMARY KEY (`id`),
  INDEX `cid` (`cid` ASC),
  INDEX `mid` (`mid` ASC))
ENGINE = MyISAM
COMMENT = '音乐表';


-- -----------------------------------------------------
-- Table `etp`.`etp_carousel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `etp`.`etp_carousel` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(20) NOT NULL DEFAULT '' COMMENT '轮播标题',
  `info` VARCHAR(300) NOT NULL DEFAULT '' COMMENT '轮播简介',
  `picurl` VARCHAR(100) NOT NULL DEFAULT '' COMMENT '图片地址',
  `link` VARCHAR(100) NOT NULL DEFAULT '' COMMENT '点击跳转地址',
  `color` VARCHAR(10) NOT NULL DEFAULT '' COMMENT '渐变颜色',
  PRIMARY KEY (`id`))
ENGINE = MyISAM
COMMENT = '首页轮播表';


-- -----------------------------------------------------
-- Table `etp`.`etp_musickeep`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `etp`.`etp_musickeep` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `keeptime` INT(10) NOT NULL DEFAULT 0 COMMENT '收藏时间',
  `mid` INT UNSIGNED NOT NULL COMMENT '被收藏音乐的ID',
  `uid` INT NOT NULL COMMENT '收藏用户的ID',
  PRIMARY KEY (`id`),
  INDEX `mid` (`mid` ASC),
  INDEX `uid` (`uid` ASC))
ENGINE = MyISAM
COMMENT = '音乐收藏表';


-- -----------------------------------------------------
-- Table `etp`.`etp_videokeep`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `etp`.`etp_videokeep` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `keeptime` INT(10) NOT NULL DEFAULT 0 COMMENT '视频收藏时间',
  `vid` INT UNSIGNED NOT NULL COMMENT '被收藏视频的ID',
  `uid` INT NOT NULL COMMENT '收藏用户的ID',
  PRIMARY KEY (`id`),
  INDEX `vid` (`vid` ASC),
  INDEX `uid` (`uid` ASC))
ENGINE = MyISAM
COMMENT = '视频收藏表';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
